name: Run Pendulum Calculation

on:
  push:
    branches:
      - main # or the branch you want this action to be triggered on

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 # or whichever version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add other required packages if necessary using pip install

    - name: Run script
      run: python perpendulum.py
